// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC32nlYaXxhkTCJIM303kUL4VDEZ6M45uM',
    appId: '1:609024851165:web:66c7fc89c782ce2cee6f34',
    messagingSenderId: '609024851165',
    projectId: 'hotelapp-5b2ff',
    authDomain: 'hotelapp-5b2ff.firebaseapp.com',
    storageBucket: 'hotelapp-5b2ff.appspot.com',
    measurementId: 'G-D7PB066G1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3veXxh4rxiiMvGp3Zg_tC4i_H3S_TGU0',
    appId: '1:609024851165:android:3f46fa4cd7959484ee6f34',
    messagingSenderId: '609024851165',
    projectId: 'hotelapp-5b2ff',
    storageBucket: 'hotelapp-5b2ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkMeg0BpDDNEEhd-Ck_EWXkcjPII0uSzg',
    appId: '1:609024851165:ios:3c1c49985442e018ee6f34',
    messagingSenderId: '609024851165',
    projectId: 'hotelapp-5b2ff',
    storageBucket: 'hotelapp-5b2ff.appspot.com',
    androidClientId: '609024851165-pq0h9j52i8hbqe9p4njbrvvfoaeari6i.apps.googleusercontent.com',
    iosClientId: '609024851165-i3po50frqc1u0ohkn8jo69tsq9atrme6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelApp',
  );
}
